### PR TITLE
exclude dto class

### PR DESCRIPTION
**Pull request by MRdevX**
Hi,
I faced an error during serialization while using the code, and found the issue.
dtoClass should be excluded from entities to make it work properly.

### CODE REVIEW

**Comment by NarHakobyan** [comment]
Hi @MRdevX, we are not serializing any entity, you need to do that only with DTOs

**Comment by MRdevX** [comment]
Thanks for your quick response :)
hmm, I'm sure I didn't use entities in the presentation layer, I used dto's in all controllers. 
Besides, I faces this issue a few days ago and I don't know how to make it happen again :))
if I could figure it out later, I'll let you know :)

**Comment by NarHakobyan** [comment]
Do you have class field which is a type of Entity? 
Can you please add a code example to get that error?

**Comment by MRdevX** [comment]
> Do you have class field which is a type of Entity?
> Can you please add a code example to get that error?

AFAIK I don't have. but I'll check it, and let you know.

**Pull request closed without merging**
