### PR TITLE
Fix Prompt for Hygen scaffolding

### PR DESCRIPTION
**Pull request by Handfish**
Presently the `yarn run new module` command runs into the following error:
```
TypeError: Cannot read properties of undefined (reading 'enabled')                                      
    at MultiSelect.enable (.../my-nest-app/node_modules/enquirer/lib/types/array.js:256:24)    
```

This fixes the bug.

### CODE REVIEW

**Comment by NarHakobyan** [comment]
Hi @Handfish, prompt functionality is not configured yet.

**Comment by Handfish** [comment]
I took a closer look into this and have made a pull request to hygen. https://github.com/jondot/hygen/issues/362

**Comment by Handfish** [comment]
This should work now.

More information:
https://github.com/jondot/hygen/issues/365
https://github.com/jondot/hygen/pull/366

**Comment by Handfish** [comment]
Honestly Plop might be something to consider. Seems like it has a much more sensible API and is being updated presently.
https://github.com/plopjs/plop which imports https://github.com/plopjs/node-plop

Having access to `actions` in plop allows for one template to generate multiple files, etc etc
```
        actions: [
          {
              type: 'add',
              path: './app/Http/Requests/{{className}}.php',
              templateFile: './.generators/templates/Request.hbs',
          }
        ]
```

**Comment by NarHakobyan** [comment]
@Handfish yeah, plop looks better, also it has a template file separated so we can have syntax highlights, could you please confirm?

**Comment by Handfish** [comment]
@NarHakobyan plop uses [handlebars](https://github.com/handlebars-lang/handlebars.js/) for templates. If you are considering switching to plop I'd recommend a new issue.

This pull request is ready and does in fact make prompt.js work the way you originally intended - so if you are comfortable using `@handfish/hygen` then I'd probably get this merged first.

**Comment by Handfish** [comment]
FYI - @handfish/hygen was merged into master if you'd like to continue looking into this

**Comment by NarHakobyan** [comment]
@Handfish sorry for late reply, I was quite busy, cool, let's merge this 🥇

**Pull request merged**
